out_dir: tests/results
metric_best: forces_mae
metric_agg: argmin
wandb:
  use: True
  project: mlff
  entity: daniel-rothenpieler-technical-university-of-munich
dataset:
  format: torch_geometric
  name: md17
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Embedding+MagLapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: GemEdge 
  edge_encoder_bn: False
posenc_MagLapPE:
  enable: True
  positional_encoding: True
  dim_pe: 8
  q: 0.
  largest_connected_component: False
  sparse: False
  max_freqs: 150
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
model:
  type: s2gnn
  loss_fun: l2
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 3
  dim_inner: 128
  layer_type: gemnet
  stage_type: stack
  batchnorm: False
  act: swish
  dropout: 0.1
  agg: sum
  use_edge_attr: True

  #---------------------<GemNet>--------------------
  num_spherical: 7
  num_radial: 6
  shared_projections: True

  #-----Has to match dim_inner for now -----------
  emb_size_atom: 128
  emb_size_edge: 128
  #-----------------------------------------------
  edge_emb_act: swish 

  emb_size_trip: 64
  emb_size_quad: 32
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 32
  emb_size_bil_trip: 64
  emb_size_bil_quad: 32

  num_before_skip: 1
  num_after_skip: 1
  num_concat: 1
  num_atom: 2
  num_output_layers: 1
  cutoff: 5.0
  #---------------------</GemNet>--------------------

  spectral:
    layer_skip: [0, 1, 2, 3, 4]
    frequency_cutoff: 0.7
    filter_encoder: basis # basis, lin, mlp or attn
    feature_transform: glu_0.05
    filter_variant: None  # None, silu or silu_mix
    window: tukey
    basis_num_gaussians: 50
    basis_bottleneck: 0.2
    num_heads_filter_encoder: 128
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 2e-6
  base_lr: 1e-3
  max_epoch: 250
  scheduler: linear_with_warmup
  num_warmup_epochs: 10
  model_averaging: ema
share:
  dim_in: 236
device: cuda
num_workers: 4
derive_forces: True
