out_dir: tests/results
metric_best: mae
metric_agg: argmin

wandb:
  use: True
  project: mlff
  entity: tugcan-hoser-technical-university-of-munich

dataset:
  format: torch_geometric
  name: coll
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Embedding+MagLapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: GemEdge
  edge_encoder_bn: False

posenc_MagLapPE:
  enable: True
  positional_encoding: True
  dim_pe: 8
  q: 0.
  largest_connected_component: False
  sparse: False
  max_freqs: 150

posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm

train:
  mode: custom
  batch_size: 32
  eval_period: 2
  ckpt_period: 100

model:
  type: s2gnn
  loss_fun: l2
  edge_decoding: dot
  graph_pooling: add

gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 3
  dim_inner: 224
  layer_type: gemnet
  use_edge_attr: True
  stage_type: stack
  batchnorm: False
  act: swish
  dropout: 0.25
  agg: sum
  cutoff: 10.0
  embedding_cutoff: 5.0          
  envelope_exponent: 5          
  force_weighting: 0.999 

  # GemNet-specific parameters
  num_spherical: 7
  num_radial: 6

  emb_size_atom: 224
  emb_size_edge: 224
  edge_emb_act: swish

  emb_size_trip: 64
  emb_size_quad: 32
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 32
  emb_size_bil_trip: 64
  emb_size_bil_quad: 32

  num_radial: 20
  num_spherical: 5
  num_before_skip: 1
  num_after_skip: 1
  num_concat: 1
  num_atom: 2
  num_output_layers: 1

  spectral:
    layer_skip: [3]
    frequency_cutoff: 1.0
    filter_encoder: basis
    feature_transform: glu_0.05
    filter_variant: None
    window: tukey
    basis_num_gaussians: 60
    basis_bottleneck: 0.2
    num_heads_filter_encoder: 128

optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.000002
  base_lr: 0.001
  model_averaging: ema
  max_epoch: 400
  scheduler: cosine_with_warmup
  num_warmup_epochs: 1

share:
  dim_in: 236

device: cpu
num_workers: 0
derive_forces: True